from django.urls import path

from .views import (
    ActiveCategoryListView,
    ActiveProductListView,
    AdminDeliveryCoverageSettingsView,
    AdminOrderAvailabilityConfigView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminRestrictedDateDetailView,
    AdminRestrictedDateListCreateView,
    AdminManualPaymentSettingsView,
    CategoryProductListView,
    DeliveryAddressValidationView,
    FeaturedProductListView,
    CourierAssignedOrderListView,
    CourierOrderStatusUpdateView,
    PublicStoreLocationView,
    OrderPaymentReceiptUploadView,
    AdminOrderPaymentDecisionView,
    OrderListCreateView,
    OrderDetailView,
    PublicManualPaymentSettingsView,
    PublicOrderAvailabilityView,
)

urlpatterns = [
    path("products/", ActiveProductListView.as_view(), name="product-list"),
    path(
        "products/featured/",
        FeaturedProductListView.as_view(),
        name="product-featured-list",
    ),
    path(
        "categories/",
        ActiveCategoryListView.as_view(),
        name="category-lis\
         t",
    ),
    path(
        "categories/<slug:slug>/products/",
        CategoryProductListView.as_view(),
        name="category-product-list",
    ),
    path(
        "admin/products/",
        AdminProductListCreateView.as_view(),
        name="admin-product-list-create",
    ),
    path(
        "admin/products/<int:pk>/",
        AdminProductDetailView.as_view(),
        name="admin-product-detail",
    ),
    path(
        "orders/",
        OrderListCreateView.as_view(),
        name="order-list-create",
    ),
    path(
        "orders/<int:pk>/payment/receipt/",
        OrderPaymentReceiptUploadView.as_view(),
        name="order-payment-receipt",
    ),
    path(
        "orders/<int:pk>/payment/<str:action>/",
        AdminOrderPaymentDecisionView.as_view(),
        name="admin-order-payment-decision",
    ),
    path(
        "orders/assigned/",
        CourierAssignedOrderListView.as_view(),
        name="order-assigned-list",
    ),
    path(
        "orders/<int:pk>/courier-status/",
        CourierOrderStatusUpdateView.as_view(),
        name="order-courier-status",
    ),
    path(
        "orders/delivery/validate/",
        DeliveryAddressValidationView.as_view(),
        name="order-delivery-validate",
    ),
    path(
        "orders/<int:pk>/",
        OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "order-availability/",
        PublicOrderAvailabilityView.as_view(),
        name="public-order-availability",
    ),
    path(
        "payment-settings/",
        PublicManualPaymentSettingsView.as_view(),
        name="public-manual-payment-settings",
    ),
    path(
        "admin/order-availability/",
        AdminOrderAvailabilityConfigView.as_view(),
        name="admin-order-availability",
    ),
    path(
        "admin/payment-settings/",
        AdminManualPaymentSettingsView.as_view(),
        name="admin-manual-payment-settings",
    ),
    path(
        "admin/restricted-dates/",
        AdminRestrictedDateListCreateView.as_view(),
        name="admin-restricted-date-list-create",
    ),
    path(
        "admin/restricted-dates/<int:pk>/",
        AdminRestrictedDateDetailView.as_view(),
        name="admin-restricted-date-detail",
    ),
    path(
        "admin/delivery-coverage/",
        AdminDeliveryCoverageSettingsView.as_view(),
        name="admin-delivery-coverage",
    ),
    path(
        "store-location/",
        PublicStoreLocationView.as_view(),
        name="public-store-location",
    ),
]
