from django.urls import path

from .views import (
    ActiveCategoryListView,
    AdminDeliveryCoverageSettingsView,
    AdminManualSaleCreateView,
    AdminManualSaleDeleteView,
    ActiveProductListView,
    AdminProductDetailView,
    AdminProductListCreateView,
    CategoryProductListView,
    DeliveryAddressValidationView,
    FeaturedProductListView,
    OrderListCreateView,
    OrderDetailView,
    SalesHistoryListView,
    SalesMetricsView,
)

urlpatterns = [
    path("products/", ActiveProductListView.as_view(), name="product-list"),
    path(
        "products/featured/",
        FeaturedProductListView.as_view(),
        name="product-featured-list",
    ),
    path(
        "categories/",
        ActiveCategoryListView.as_view(),
        name="category-lis\
         t",
    ),
    path(
        "categories/<slug:slug>/products/",
        CategoryProductListView.as_view(),
        name="category-product-list",
    ),
    path(
        "admin/products/",
        AdminProductListCreateView.as_view(),
        name="admin-product-list-create",
    ),
    path(
        "admin/products/<int:pk>/",
        AdminProductDetailView.as_view(),
        name="admin-product-detail",
    ),
    path(
        "admin/delivery-coverage/",
        AdminDeliveryCoverageSettingsView.as_view(),
        name="admin-delivery-coverage",
    ),
    path(
        "orders/",
        OrderListCreateView.as_view(),
        name="order-list-create",
    ),
    path(
        "orders/delivery/validate/",
        DeliveryAddressValidationView.as_view(),
        name="delivery-address-validate",
    ),
    path(
        "orders/<int:pk>/",
        OrderDetailView.as_view(),
        name="order-detail",
    ),
    path(
        "admin/sales/history/",
        SalesHistoryListView.as_view(),
        name="admin-sales-history",
    ),
    path(
        "admin/sales/metrics/",
        SalesMetricsView.as_view(),
        name="admin-sales-metrics",
    ),
    path(
        "admin/sales/register/",
        AdminManualSaleCreateView.as_view(),
        name="admin-sales-register",
    ),
    path(
        "admin/sales/<int:pk>/",
        AdminManualSaleDeleteView.as_view(),
        name="admin-sales-delete",
    ),
]
