# Generated by Django 6.0.2 on 2026-04-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_order_created_by_order_order_source"),
        ("catalog", "0004_order_user"),
    ]

    operations = []
