# Generated by GitHub Copilot on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_merge_20260415_1148"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCoverageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Cobertura principal", max_length=120),
                ),
                (
                    "local_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "local_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "max_delivery_km",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("coverage_note", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracion de cobertura",
                "verbose_name_plural": "Configuracion de cobertura",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="address_validation_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="address_validation_status",
            field=models.CharField(
                choices=[
                    ("not_validated", "No validada"),
                    ("valid", "Valida"),
                    ("invalid", "Invalida"),
                    ("out_of_coverage", "Fuera de cobertura"),
                    ("service_error", "Error de servicio"),
                ],
                default="not_validated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_maps_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
