# Generated by GitHub Copilot on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_delivery_coverage_and_order_geo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycoveragesettings",
            name="local_address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverycoveragesettings",
            name="local_city",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverycoveragesettings",
            name="local_country",
            field=models.CharField(default="Colombia", max_length=120),
        ),
        migrations.AddField(
            model_name="deliverycoveragesettings",
            name="local_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deliverycoveragesettings",
            name="local_region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="deliverycoveragesettings",
            name="local_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliverycoveragesettings",
            name="local_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
            ),
        ),
    ]
