# Generated by ChatGPT

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_refine_featured_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAvailabilityConfig",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pickup_weekday_open",
                    models.TimeField(default=datetime.time(9, 0)),
                ),
                (
                    "pickup_weekday_close",
                    models.TimeField(default=datetime.time(20, 0)),
                ),
                (
                    "pickup_sunday_open",
                    models.TimeField(default=datetime.time(8, 0)),
                ),
                (
                    "pickup_sunday_close",
                    models.TimeField(default=datetime.time(20, 0)),
                ),
                (
                    "delivery_weekday_open",
                    models.TimeField(default=datetime.time(9, 0)),
                ),
                (
                    "delivery_weekday_close",
                    models.TimeField(default=datetime.time(19, 30)),
                ),
                (
                    "delivery_sunday_open",
                    models.TimeField(default=datetime.time(8, 0)),
                ),
                (
                    "delivery_sunday_close",
                    models.TimeField(default=datetime.time(19, 30)),
                ),
                ("order_notice", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de horarios",
                "verbose_name_plural": "Configuración de horarios",
            },
        ),
        migrations.CreateModel(
            name="RestrictedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all", "Todas las modalidades"),
                            ("pickup", "Recoger en sede"),
                            ("delivery", "Domicilio"),
                            ("scheduled", "Programado"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Día restringido",
                "verbose_name_plural": "Días restringidos",
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="restricteddate",
            constraint=models.UniqueConstraint(
                fields=("date", "applies_to"),
                name="catalog_restricted_date_unique_date_applies_to",
            ),
        ),
    ]
