# Generated by Django 6.0.2 on 2026-04-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_ordernotification"),
        ("catalog", "0007_delivery_coverage_address_fields"),
    ]

    operations = []
