# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_orderavailabilityconfig_restricteddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderavailabilityconfig",
            name="is_accepting_orders",
            field=models.BooleanField(default=True),
        ),
    ]
