# Generated by Django 6.0.2 on 2026-04-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_merge_20260415_1200"),
        ("catalog", "0008_orderavailabilityconfig_is_accepting_orders"),
    ]

    operations = []
