# Generated by Django 6.0.2 on 2026-04-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_merge_20260420_1713"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ordernotification",
            name="catalog_orde_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordernotification",
            name="catalog_orde_order_id_status_idx",
        ),
        migrations.DeleteModel(
            name="OrderNotification",
        ),
    ]
