# Generated by Django 5.1.4 on 2026-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_manual_payment_settings_and_receipts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmado"),
                    ("preparing", "En preparación"),
                    ("ready", "Listo"),
                    ("in_transit", "En camino"),
                    ("completed", "Completado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
