services:

  front:

    build:
      context: .
      dockerfile: frontend/Dockerfile

    volumes:
      - ./frontend:/app/frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    networks:
      - backend_network

  backend:

    build:
      context: .
      dockerfile: backend/Dockerfile

    volumes:
      - ./backend:/app/backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      - PYTHONPATH=/app

    command: >
      sh -c "
      echo 'Esperando base de datos...' &&
      python backend/wait_for_db.py &&
      echo 'Base de datos lista ✅' &&
      python backend/manage.py migrate &&
      echo 'Iniciando servidor Django...' &&
      echo '🚀 Django corriendo en: http://localhost:8080' &&
      python backend/manage.py runserver 0.0.0.0:8080
      "

    depends_on:
      - postgres

    networks:
      - backend_network

  postgres:

    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
