#!/usr/bin/env sh
set -e

echo "Running frontend checks..."
cd frontend
npm run lint
npm run format:check
npm run typecheck
cd ..

echo "Running backend quality checks..."
flake8 .
black --check --diff .
bandit -c bandit.yaml -r .
